spring:
  application:
    name: equipment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/equipment_db}
    username: ${DB_USERNAME:equipment}
    password: ${DB_PASSWORD:equipment}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081
  forward-headers-strategy: framework

application:
  api-path: /api
  internal-path: /internal

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: Equipment Service
    java: 17
services:
  maintenance:
    base-url: ${MAINTENANCE_SERVICE_URL:http://localhost:8082}
    cache-ttl: ${MAINTENANCE_CACHE_TTL:5s}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
    urls-primary-name: "Публичное API оборудования"
  api-docs:
    path: /v3/api-docs
